server:
  port: 8820
  servlet:
    context-path: /cmf
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sql?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: utf-8
      force: true
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cmf/hcguot/estate_management_system/entity